services:

  mysql:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${BD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}

  backend:
    build:
      context: .
      args:
        JAVA_FILE: target/*.jar 
    container_name: backend-app
    environment:
      BD_HOST: mysql
      BD_PORT: 3306
      BD_USER: ${USER}
      BD_PASS: ${PASSWORD}
      BD_DATABASE: ${BD}
    restart: always
    depends_on:
      - mysql
    ports:
      - 80:7070


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
